// app2/src/components/Footer.vue
<template>
  <footer class="footer">
    <p>Stay ahead and be focused.</p>
    <p>&copy; Copyright 2018 -
      <a href="https://www.linkedin.com/in/windmaomao" target="_blank">Fang Jin</a>
    </p>
  </footer>
</template>

<script>
export default {
  name: 'Footer'
}
</script>

<style scoped>
.footer {
  position: relative;
  font-size: 90%;
  font-style: italic;
  z-index: 1000;
}
.footer p {
  text-align: center;
}
</style>

// app3/src/Footer.tsx
import * as React from 'react';

class Footer extends React.Component {
  render() {
    return (
      <footer className="footer">
        <p>Stay ahead and be focused.</p>
        <p>&copy; Copyright 2018 -
          <a href="https://www.linkedin.com/in/windmaomao" target="_blank">Fang Jin</a>
        </p>
      </footer>
    );
  }
}

export default Footer;
